### PR TITLE
FIXED: Remove items from cart

### PR DESCRIPTION
**Pull request by AubryFreeman**
***Back-end merge required for front-end to work** 

Fixed bug where user was not able to remove items from cart. Also fixed bug where users weren't able to add items to car

## Changes

- bangazon/urls.py now has a urlpattern for add_to_cart

## Requests / Responses

**Request**

## Testing

Users are now able to remove items from their cart

- [ ] Navigate to products
- [ ] Click on a product
- [ ] Add to cart
- [ ] Click on the trash icon

## Related Issues

- Fixes [#46](https://github.com/NSS-Day-Cohort-68/bangazon-client-bangazon-client-bangazon-team-3/issues/46)

### CODE REVIEW

**Review by sgriff22 — CHANGES_REQUESTED** [review]
I cannot test the backend code with the UI because your client side changes has not been merged and is still sending errors. Can you give me instructions with postman?

**Comment by AubryFreeman** [comment]
> I cannot test the backend code with the UI because your client side changes has not been merged and is still sending errors. Can you give me instructions with postman?

In POSTMAN

Create a POST request

Enter the following url
http://localhost:8000/profile/cart

In the body enter the following info in raw format
```json
{
    "product_id": 11
}
```
Once you send the request the following response should be displayed

```json
{
    "id": 24,
    "product": {
        "id": 146,
        "name": "Utility Knife",
        "price": 5.58,
        "number_sold": 0,
        "description": "A sharp utility knife with replaceable blades",
        "quantity": 3,
        "created_date": "2023-03-14",
        "location": "Workshop",
        "image_path": "http://localhost:8000/media/products/tools.png",
        "average_rating": 0
    }
}
```
with a status code of 200 OK
(some info might be different for you)

Confirm in your sqlite3 under the orderproduct table that the product was posted

Once you get your response from the POST copy it and open a DELETE Request

enter the following url
http://localhost:8000/cart/146

note: the URL depends on which product id you are trying to delete.

in the body enter your response from the previous POST request

```json
{
    "id": 23,
    "product": {
        "id": 146,
        "name": "Utility Knife",
        "price": 5.58,
        "number_sold": 0,
        "description": "A sharp utility knife with replaceable blades",
        "quantity": 3,
        "created_date": "2023-03-14",
        "location": "Workshop",
        "image_path": "http://localhost:8000/media/products/tools.png",
        "average_rating": 0
    }
}
```

Once you send the request you should see the following in the response 

``` json
{}
```
with a 204 No Content

Confirm in your sqlite3 under the orderproduct table that it has been removed

**Comment by sgriff22** [comment]
I tested the Delete functionality and unfortunately, it deletes the whole cart/ all the orderProducts. I believe we only want to delete the one item.

**Review by sgriff22 — APPROVED** [review]
Tested and it's all working!

**Pull request merged**
